//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTDETAILS
    {
        public int ContactId { get; set; }
        public string Street { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Pincode { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Telephone { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public string Email { get; set; }
    }
}
