//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMERGENCYCONTACT
    {
        public int EmergencyContactId { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public Nullable<decimal> Telephone { get; set; }
        public Nullable<decimal> Mobile { get; set; }
    }
}
