//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EmployeeId { get; set; }
        public Nullable<int> PersonalDetailId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> EmergencyContactId { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> JobtitleId { get; set; }
    }
}
