//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTRECORD
    {
        public int PaymentID { get; set; }
        public Nullable<int> PaymentMonth { get; set; }
        public Nullable<int> PaymentYear { get; set; }
        public string EmployeeId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> BasicPay { get; set; }
        public Nullable<int> HRA { get; set; }
        public Nullable<int> TA { get; set; }
        public Nullable<int> OtherAllowances { get; set; }
        public Nullable<int> EPF { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> Absence { get; set; }
    }
}
